# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
# It will test the standalone setup of the orchestrator-core-gui

name: Lint and test the GPL version

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'
  workflow_call:
  pull_request:

jobs:
  build:
    name: Check lint, yarn, test and compile errors
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: yarn prettier
      - run: rm -rf src/custom-surf
      - run: mv src/custom-example src/custom
      - run: yarn test
      - run: yarn build
