# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
# It will test the SURF specific setup of the orchestrator-core-gui
#
# Note: Linting is done via the `test-standalone.yml` workflow

name: Lint and test the SURF version

on:
  push:
  workflow_call:

jobs:
  build:
    name: Check yarn, test and compile errors
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --frozen-lockfile
      - run: mv src/custom-surf src/custom
#      - run: yarn test
      - run: yarn build
